[build]
  publish = "build/"
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-csp-generator"
 
  [plugins.inputs]
  buildDir = "dist"  // the path for the publish directory in Netlify
 
  [plugins.inputs.policies]
    defaultSrc = "'self'"
    styleSrc = "'self' 'unsafe-hashes'"