[build]
  publish = "build/"
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-csp-generator"
 
  [plugins.inputs]
  buildDir = "dist" 
  
  [plugins.inputs.policies]
    defaultSrc = "*"
    styleSrc = "*"
    script-src = "*"
    connect-src = "*"
    img-src = "*"
    base-uri = "*"
    form-action = "*"